Pr/decouple xserver
ArcticaProject/nx-libs pull request #208
Opened 2016-09-29 09:56 UTC by uli42

- 
- Use own copies of xkb headers just as upstream does.
- refer to Xtrans via header file xstrans.c instead of softlinking in the makefile
- backport fixes for some compiler warnings that became obvious after the xstrans switch. These happened to be CVEs...

2016-10-01 09:43 UTC, sunweaver requested changes

2016-10-01 09:43 UTC, sunweaver commented on nx-X11/programs/Xserver/dix/devices.c
> +#include <xkbsrv.h>
Please use "xkbsrv.h" instead here.

2016-10-01 09:43 UTC, sunweaver commented on nx-X11/programs/Xserver/dix/dispatch.c
> +#include <xkbsrv.h>
same here... (quotation marks instead of pointed brackets)

2016-10-01 09:43 UTC, sunweaver commented on nx-X11/programs/Xserver/dix/events.c
> +#include <xkbsrv.h>
same here...

2016-10-01 09:43 UTC, sunweaver commented on nx-X11/programs/Xserver/dix/devices.c
> +#include <xkbsrv.h>
is it correct to have no captial letters in this filename? XKBsrv.h vs. xkbsrv.h?

2016-10-01 09:43 UTC, sunweaver commented on nx-X11/programs/Xserver/hw/nxagent/Keyboard.c
> +#include <nx-X11/extensions/XKBstr.h>
and why XKBsrv.h here? As I understand,the XKBsrv.h version is libX11 whereas the xkbsrv.h is Xserver. Which one is actually needed here? (I feel, it should be xkbsrv.h here, but that is just a gut feeling).

2016-10-01 09:43 UTC, sunweaver commented on nx-X11/programs/Xserver/os/utils.c
> +#include <xkbsrv.h>
same here... (I won't mark any more of these, please make sure to fix all occurrences)

2016-10-01 09:44 UTC, sunweaver commented
uli42: thanks for filing this PR. Please go through my individual comments. When done, please make sure you rebase this PR branch against 3.6.x. There are some commits that are already available on the 3.6.x branch, so they should not appear in this PR anymore.

THANKS!
Mike

2016-10-01 14:21 UTC, uli42 commented
Regarding quotes vs brackets: I wanted to stay as close to upstream as possible. 

Also the naming of the header files is from upstream. The two files with XKBsrv.h need the client side headers. 

Vom Smartphone gesendet.

----- Ursprüngliche Nachricht -----
Von: "Mike Gabriel" <notifications@github.com>
Gesendet: ‎01.‎10.‎2016 11:43
An: "ArcticaProject/nx-libs" <nx-libs@noreply.github.com>
Cc: "Ulrich Sibiller" <uli42@gmx.de>; "Author" <author@noreply.github.com>
Betreff: Re: [ArcticaProject/nx-libs] Pr/decouple xserver (#208)

@sunweaver requested changes on this pull request.



In nx-X11/programs/Xserver/dix/devices.c:
> @@ -63,7 +63,7 @@ SOFTWARE.
 #include "site.h"
 #define	XKB_IN_SERVER
 #ifdef XKB
-#include <nx-X11/extensions/XKBsrv.h>
+#include <xkbsrv.h>
Please use "xkbsrv.h" instead here.



In nx-X11/programs/Xserver/dix/dispatch.c:
> @@ -111,7 +111,7 @@ int ProcInitialConnection();
 #ifdef XKB
 #define XKB_IN_SERVER
 #include "inputstr.h"
-#include <nx-X11/extensions/XKBsrv.h>
+#include <xkbsrv.h>
same here... (quotation marks instead of pointed brackets)



In nx-X11/programs/Xserver/dix/events.c:
> @@ -129,7 +129,7 @@ of the copyright holder.
 #include "globals.h"
 
 #ifdef XKB
-#include <nx-X11/extensions/XKBsrv.h>
+#include <xkbsrv.h>
same here...



In nx-X11/programs/Xserver/dix/devices.c:
> @@ -63,7 +63,7 @@ SOFTWARE.
 #include "site.h"
 #define	XKB_IN_SERVER
 #ifdef XKB
-#include <nx-X11/extensions/XKBsrv.h>
+#include <xkbsrv.h>
is it correct to have no captial letters in this filename? XKBsrv.h vs. xkbsrv.h?



In nx-X11/programs/Xserver/hw/nxagent/Keyboard.c:
> @@ -75,6 +75,7 @@ is" without express or implied warranty.
 
 #define XKBSRV_NEED_FILE_FUNCS
 #include <nx-X11/extensions/XKBsrv.h>
+#include <nx-X11/extensions/XKBstr.h>
and why XKBsrv.h here? As I understand,the XKBsrv.h version is libX11 whereas the xkbsrv.h is Xserver. Which one is actually needed here? (I feel, it should be xkbsrv.h here, but that is just a gut feeling).



In nx-X11/programs/Xserver/os/utils.c:
> @@ -141,7 +141,7 @@ OR PERFORMANCE OF THIS SOFTWARE.
 #endif
 
 #ifdef XKB
-#include <nx-X11/extensions/XKBsrv.h>
+#include <xkbsrv.h>
same here... (I won't mark any more of these, please make sure to fix all occurrences)
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.

2016-10-01 18:26 UTC, sunweaver commented
>Regarding quotes vs brackets: I wanted to stay as close to upstream as possible. Maybe I overlooked 
> some places, will re-check.

Pointed brackets really look incoherent here. Maybe we should not adopt that from X.org.

> Also the naming of the header files is from upstream.

This is ok then. I just wanted to make sure filenames are not mixed up.

> [...]

I trust your judement on the rest of your comment.

Thanks!
Mike

2016-10-01 18:26 UTC, sunweaver commented
Make sure, you really rebase your branch against latest 3.6.x. I pushed some merges and close some PRs.

2016-10-04 19:37 UTC, uli42 commented on nx-X11/programs/Xserver/dix/dispatch.c
> +#include <xkbsrv.h>
I have now checked includes and adapted to upstream. While you are probably right in respect to quotes against brackets I prefer to stay as close as possible to upstream. Upstream is not really coherent in that respect, too...

2016-10-04 19:39 UTC, uli42 commented
I have now checked includes and adapted to upstream. While you are probably rightregarding quotes against brackets I prefer to stay as close as possible to upstream. Upstream is not really coherent in that respect, too...

2016-10-07 19:35 UTC, sunweaver approved these changes

2016-10-07 19:38 UTC, merged