Pr/upgrade lib x11
ArcticaProject/nx-libs pull request #214
Opened 2016-10-05 14:26 UTC by uli42

New attempt to upgrade to libX11 1.3.4

This is the result of splitting up and reworking #195. This pr only concentrates on libX11 where the previous attempt also changed parts of xserver.

2016-10-07 19:48 UTC, sunweaver commented
This PR has unresolved conflicts. Please resolve (and rebase against latest 3.6.x) and ping me again. Thanks.

2016-10-08 21:58 UTC, sunweaver requested changes
Hi Ulrich,

I left various comments. Most of them require being fixed. Please take a look at let me know if you agree.

Thanks,
Mike

2016-10-08 21:58 UTC, sunweaver commented on nx-X11/lib/X11/XKBlib.h
> +#if !defined(_XKBLIB_H_) && !defined(_X11_XKBLIB_H)
This fixes issue #174, please add

```
Fixes ArcticaProject/nx-libs#174.
```

to the commit msg.

2016-10-08 21:58 UTC, sunweaver commented on nx-X11/lib/X11/XlibInt.c
> -#if defined(NX_TRANS_SOCKET) && defined(NX_TRANS_CHANGE)
XlibInt.c, old file version line 789ff. Why did you remove the NX related code here?

2016-10-08 21:58 UTC, sunweaver commented on nx-X11/lib/X11/XlibInt.c
> -/*
AFAICT, this introduces a regression. _XEatDataWords symbol must continue to exist in libNX_X11, so libXrender does not fail when using it.

2016-10-08 21:58 UTC, sunweaver commented on nx-X11/lib/X11/XlibInt.c
> -/*
AFAICT, this introduces a regression. _XEatDataWords symbol must continue to exist in libNX_X11, so libXrender does not fail when using it.

2016-10-08 21:58 UTC, sunweaver commented on nx-X11/lib/X11/Xlibint.h
> -extern void _XEatDataWords(
Same here, don't drop _XEatDataWords

2016-10-08 21:58 UTC, sunweaver commented on nx-X11/lib/X11/XlibInt.c
> -#if (defined(_POSIX_SOURCE) && !defined(AIXV3) && !defined(__QNX__)) || defined(hpux) || defined(USG) || defined(SVR4)
What is the USG definition? If we remove it here, shouldn't we remove it all over the nx-libs source tree?

Personally, I'd say we leave it in place here and do another clean-up run that removed USG support everywhere.

2016-10-08 21:58 UTC, sunweaver commented on nx-X11/lib/X11/XlibInt.c
> -void *_XGetRequest(Display *dpy, CARD8 type, size_t len)
Don't remove this. It will cause a regression. You yourself added this some weeks ago to fix crashes in libXrender IIRC.

2016-10-08 21:58 UTC, sunweaver commented on nx-X11/config/cf/X11.tmpl
> +    XLOCALELIBDIR = XlocaleDir          /* FIXME: For now take XLOCALDIR, unsure about the correct setting */
typo in comment XLOCALDIR -> XLOCALEDIR

2016-10-08 21:58 UTC, sunweaver commented on nx-X11/lib/X11/SetLocale.c
> +#if defined(__APPLE__) || defined(__CYGWIN__)
Shouldn't we stick to using __DARWIN__ here? Or do the Imakefiles somewhere also define __APPLE__?

2016-10-08 21:58 UTC, sunweaver commented on nx-X11/lib/X11/XlibInt.c
> +#ifdef NX_TRANS_SOCKET
Why does this commit touch XlibInt.c at all? Why does NX'ish code get re-added in this commit. As I understand it, you basically have to commits for the 1.3.4 version bump.

One commit brings all 1.3.4 updates into files that had been modified for NX back then. And in the second commit (this one), you copy in all files from 1.3.4 that never had to be adapted for NX. So, this second commit should not touch the XlibInt.c file (all 1.3.4 backports should be in the first commit, referenced above).

Right?

2016-10-08 21:58 UTC, sunweaver commented on nx-X11/lib/X11/XlibInt.c
> +#if defined(NX_TRANS_SOCKET) && defined(NX_TRANS_DEBUG)
Same here.

2016-10-08 21:58 UTC, sunweaver commented on nx-X11/lib/X11/XlibInt.c
> +#ifdef NX_TRANS_SOCKET
And here... Please check all NX_ occurences in this commit. Won't comment on more occurrences.

2016-10-08 21:58 UTC, sunweaver commented on nx-X11/lib/X11/XlibInt.c
> +void _XEatDataWords(Display *dpy, unsigned long n)
_XEatDataWords reintroduced here. Should not have gotten removed in 9c9fe36040a8672608ff8cac2e711d1891f50d47.

2016-10-08 21:58 UTC, sunweaver commented on nx-X11/lib/X11/XlibInt.c
> +void *_XGetRequest(Display *dpy, CARD8 type, size_t len)
_XGetRequest re-introduced here. Should not have gotten removed in 9c9fe36040a8672608ff8cac2e711d1891f50d47.

2016-10-08 21:58 UTC, sunweaver commented on nx-X11/lib/X11/XlibInt.c
> +#include <nx-X11/Xmd.h>  /* for LONG64 on 64-bit platforms */
This should not be necessary anymore since 35e8c02d9c64e6d15e33dfee1f13c6cb94d4108b. Right?

2016-10-08 21:58 UTC, sunweaver commented on nxcomp/Loop.cpp
> +        if (ParseHostOption(nextArg, cHost, cPort) > 0)
This commit should not be in this PR. Please rebase properly against 3.6.x.

2016-10-08 21:58 UTC, sunweaver commented on nxcomp/Loop.cpp
> +      if (unixPath && unixPath[0] != '\0' )
Dito. Please rebase properly against 3.6.x.

2016-10-08 21:58 UTC, sunweaver commented on nx-X11/lib/X11/Xlib.h
> +#endif /* _XLIB_H_ */
Shouldn't this be

```
#endif /* !_XKBLIB_H_ && !_X11_XKBLIB_H */
```

or such?

2016-10-08 21:58 UTC, sunweaver commented on nx-X11/lib/X11/XlibAsync.c
> +
It seems XlibAsync.c has only one occurrence of NX_* macros and that one is a noop macro.

Personally, I'd say: drop the passage with the NX_* macro from XlibAsync.c and the we can drop our copyright for XlibAsync.c, as well.

2016-10-08 21:58 UTC, sunweaver commented on nx-X11/lib/X11/XKeysymDB
> +XF86TouchpadOff		:1008FFB1
White-space only, not making sense. Please don't.

2016-10-08 21:59 UTC, sunweaver commented
Reminder for merging: This PR should somehow close #157.

2016-10-09 09:07 UTC, uli42 commented on nx-X11/lib/X11/XlibInt.c
> +#include <nx-X11/Xmd.h>  /* for LONG64 on 64-bit platforms */
Yeah, but I'll leave it for now. I have acted like that fix was not included yet. We should keep this clean until we fix it with one great commit.

2016-10-09 09:25 UTC, uli42 commented on nx-X11/lib/X11/XlibInt.c
> +#ifdef NX_TRANS_SOCKET
Well, I do not remember details, but some comments:
1. lots of changes are only formatting/whitespace changes
2. there also also optimizations where I saw that I could some lines
3. I remember it had been quite complicated to introduce the XKB ifdefs while maintaining hte NX ifdefs. Obviously I had done some mistakes and/or forgotten some changes in the previous commit which I fixed in this commit.

I should probably clean that up.

2016-10-09 09:28 UTC, uli42 commented on nx-X11/lib/X11/XlibInt.c
> +#if defined(NX_TRANS_SOCKET) && defined(NX_TRANS_DEBUG)
I had introduced these whitespaces to no lose track of the ifdefs (it's a jungle with all those interleaved ifdefs...) Which I decided to undo at this stage.

2016-10-09 09:29 UTC, uli42 commented on nx-X11/lib/X11/XlibInt.c
> +void *_XGetRequest(Display *dpy, CARD8 type, size_t len)
also right

2016-10-09 09:32 UTC, uli42 commented on nx-X11/lib/X11/XlibInt.c
> -#if defined(NX_TRANS_SOCKET) && defined(NX_TRANS_CHANGE)
This was by mistake.

2016-10-09 09:36 UTC, uli42 commented on nx-X11/lib/X11/XlibInt.c
> -/*
Well, again a mistake.

2016-10-09 09:38 UTC, uli42 commented on nx-X11/lib/X11/XlibInt.c
> -#if (defined(_POSIX_SOURCE) && !defined(AIXV3) && !defined(__QNX__)) || defined(hpux) || defined(USG) || defined(SVR4)
It had been removed upstream. I have not bothered removing it all over the place as I was concentrating on the libX11 backport stuff. Your suggestion is valid, will do so.

2016-10-09 09:41 UTC, uli42 commented on nx-X11/lib/X11/Xlibint.h
> -extern void _XEatDataWords(
Yes, all that has been fixed in the following commit. I will try to move these changes to to the right commit

2016-10-09 10:02 UTC, uli42 commented on nxcomp/Loop.cpp
> +      if (unixPath && unixPath[0] != '\0' )
hm, strange, my code has this.

2016-10-09 10:04 UTC, uli42 commented on nxcomp/Loop.cpp
> +        if (ParseHostOption(nextArg, cHost, cPort) > 0)
same here: strange

2016-10-09 10:09 UTC, uli42 commented
I have fixed all this an force pushed a new version. Please check.

2016-10-09 10:31 UTC, uli42 commented on nx-X11/lib/X11/XlibAsync.c
> +
I had considered that, too, but at second thought this comment is there for a reason. So I'll leave it.

2016-10-09 10:35 UTC, uli42 commented on nx-X11/lib/X11/XKeysymDB
> +XF86TouchpadOff		:1008FFB1
Yes, it make sense. With a tab size of 8 the previous version looked ugly, now it look good.

2016-10-09 15:34 UTC, uli42 commented on nx-X11/lib/X11/SetLocale.c
> +#if defined(__APPLE__) || defined(__CYGWIN__)
Hmm, upstream switched from DARWIN to APPLE in 2007 (https://cgit.freedesktop.org/xorg/lib/libX11/patch/src/SetLocale.c?id=b57129ef324c73ee91c2a796b800c4b45f4d4855), so maybe we should switch everywhere, too

2016-10-10 13:51 UTC, sunweaver requested changes
@uli42: I left some more comments behind. However, I changed network while doing that, so I will have to check if all review comments made it into the comm log history of this PR.

2016-10-10 13:51 UTC, sunweaver commented on nx-X11/lib/X11/Xlibint.h
> -extern void _XEatDataWords(
@uli42: the _XEatDataWords prototype should not get removed here. You later on add it in 13be6c792902dbb5a728ad2ec431f6ed80aa678d. Please drop the remove/add commits from this and the referenced commit (commit msg: "Xlibint.h: add missed part").

2016-10-10 13:51 UTC, sunweaver commented on nx-X11/lib/X11/XlibInt.c
> +#include <nx-X11/Xmd.h>  /* for LONG64 on 64-bit platforms */
Ok.

2016-10-10 13:51 UTC, sunweaver commented on nx-X11/lib/X11/SetLocale.c
> +#if defined(__APPLE__) || defined(__CYGWIN__)
DARWIN and APPLE. Good. That makes the code more re-usable. I play with the though of porting it to automake soon.

2016-10-10 13:51 UTC, sunweaver commented on nx-X11/lib/X11/XKeysymDB
> +XF86TouchpadOff		:1008FFB1
Ok.

2016-10-10 13:51 UTC, sunweaver commented on nx-X11/lib/X11/Xlibint.h
> +#endif
This _XEatDataWords prototype should not be in this commit.

2016-10-10 13:51 UTC, sunweaver commented on nx-X11/lib/X11/Xlibint.h
> +#endif
And... why not move this commit into one of the previous commits? Seems like a follow up fix for some previous flaw, right?

2016-10-10 13:52 UTC, sunweaver commented
@uli42: all comments made it here, so let's go into another recursion, ok. We are nearly there.

2016-10-10 21:03 UTC, uli42 commented on nx-X11/lib/X11/Xlibint.h
> +#endif
Turns out there's a upstream commit for that X_COLD stuff (https://cgit.freedesktop.org/xorg/lib/libX11/commit/include/X11/Xlibint.h?id=3fe4bea086149f06a142a8f1d575f627ec1e22c7). I have  integrated it now.

2016-10-10 21:20 UTC, uli42 commented
OK, all changes done, next iteration can start ;-)

2016-10-12 06:33 UTC, merged