Slave channel implementation
ArcticaProject/nx-libs pull request #232
Opened 2016-10-18 07:29 UTC by vatral

This is the slave channel implementation we use at QVD. 

When the channel is enabled, and the NX_SLAVE_CMD environment variable is set to a command, the agent or the proxy listens on a port, and the connection is directed to the opposite side, where the command is invoked and a bidirectional channel is created to it.

2016-10-18 07:34 UTC, uli42 commented
On Tue, Oct 18, 2016 at 9:29 AM, Vadim Troshchinskiy
<notifications@github.com> wrote:
> This is the slave channel implementation we use at QVD.
>
> When the channel is enabled, and the NX_SLAVE_CMD environment variable is set to a command, the agent or the proxy listens on a port, and the connection is directed to the opposite side, where the command is invoked and a bidirectional channel is created to it.

What are you using it for?

Uli

2016-10-18 08:08 UTC, sunweaver requested changes
Hi Vadim, I'd also be interested in how you use this patch. I don't see any problems with merging it except from the variable naming commented on above.

2016-10-18 08:08 UTC, sunweaver commented on nxcomp/Proxy.cpp
> +  char *qvd_slave_cmd = getenv("NX_SLAVE_CMD");
No QVD, X2Go, Arctica specific var names, please. Let's keep nx-libs independent (regarding namespacing) from our products.

2016-10-18 18:17 UTC, sunweaver commented
@vatral: You also had a merge commit in your PR. Please provide a "clean" PR branch! Rebased against latest 3.6.x branch and without branching cruft. Thanks!

2016-10-19 13:44 UTC, vatral commented on nxcomp/Proxy.cpp
> +  char *qvd_slave_cmd = getenv("NX_SLAVE_CMD");
Oops. I fixed the environment var, but forgot about the variable name.

By the way, does using an environment variable sound good to you?

2016-10-19 13:50 UTC, vatral commented
@uli42, @sunweaver 

We use it for communication between the VM and the client side. A connection can be established either way, client to VM, or VM to client. The handler we use is a small HTTP server that implements multiple commands.

It's being used for USB forwarding, TCP port forwarding, serial port forwarding, file sharing over sshfs, checking the version on the other side, and has a few optional debug commands (equivalents of ping, echo, discard and chargen) for network testing.

We recently found an issue with session suspend, so I will be updating this with a fix soon.

2016-10-19 19:24 UTC, sunweaver commented
@vatral: please clean up the PR branch (no merges on the branch as part of the PR).

And also, as an idea... please add some documentation of the NX_SLAVE_CMD env var to the nxproxy man page and the --help output of nxproxy. Thanks.

2016-10-24 12:47 UTC, vatral commented
@sunweaver Rebase done, manpage edited.

2016-10-28 05:30 UTC, sunweaver commented
@vatral: please rebase once more against latest 3.6.x branch. This PR is next in my queue...

2016-10-28 10:59 UTC, sunweaver commented
Hi Vadim,

I looked through this PR once more. Do I see it correctly, that you can attach a slave cmd to each channel of an nxcomp based application (i.e., proxy / agent)? Is it then sufficient to have one NX_SLAVE_CMD env variable?

This seems that NX_SLAVE_CMD must be a multi plexer, right? How does the NX_SLAVE_CMD then know to what channel it is attached?

Can you add an example script to testscripts that illustrates this feature?

2016-10-28 11:01 UTC, sunweaver commented on nxcomp/Misc.cpp
> +               port and forward the connection to the NX_SLAVE_CMD\n\
Shouldn't we replace "port" by "socket" here?  The word port may be misleading and people assume, that there will be some IP port being opened when using this NX_SLAVE_CMD feature.

2016-10-28 12:25 UTC, vatral commented on nxcomp/Misc.cpp
> +               port and forward the connection to the NX_SLAVE_CMD\n\
No, it's actually a TCP port

2016-10-28 12:33 UTC, vatral commented on nxcomp/Misc.cpp
> +               port and forward the connection to the NX_SLAVE_CMD\n\
And yes, the command is a multiplexer. In our particular usage, it's an HTTP server. So it works like this:

GET /ping
Pong!

POST /tcp/connect/4000
(slave handler execs socat, now the connection starts talking to port 4000)

I made a little test script that works on the same principle, just without HTTP and without using our libraries. I will add it to testscripts.

2016-10-28 12:48 UTC, merged