extmod / Xfree86loader cleanup
ArcticaProject/nx-libs pull request #251
Opened 2016-10-29 10:08 UTC by sunweaver

This PR completes the XFree86LOADER clean-up (see PR #249 and Issue #246).

Please remember to close #246 when merging this PR.

2016-10-30 20:29 UTC, sunweaver commented
@uli42: please review #251. Thanks.

2016-10-30 20:55 UTC, uli42 requested changes

2016-10-30 20:55 UTC, uli42 commented on nx-X11/programs/Xserver/randr/randr.c
> +
please remove leftover empty lines

2016-10-30 20:55 UTC, uli42 commented on nx-X11/programs/Xserver/fb/fb24_32.c
>  #ifdef XFree86LOADER
forgot to remove XFree86LOADER?

2016-10-30 20:55 UTC, uli42 commented on nx-X11/programs/Xserver/GL/glx/glxscreens.c
> +
superfluous empty line

2016-10-30 20:55 UTC, uli42 commented on nx-X11/programs/Xserver/Xext/Imakefile
> -
DoLoadableServer changes might conflict with https://github.com/uli42/nx-libs/commit/df6e43da96985e41366d06583786b64b25577939 from my PR #267

2016-10-30 22:45 UTC, sunweaver commented on nx-X11/programs/Xserver/Xext/Imakefile
> -
I will merge #267 first and then rebase this PR.

2016-10-30 23:03 UTC, sunweaver commented
On  So 30 Okt 2016 21:44:43 CET, Ulrich Sibiller wrote:

> uli42 commented on this pull request.
>
>
>
>> @@ -27,9 +27,9 @@
>  #include <dix-config.h>
>  #endif
>
> +#include <string.h>
>  #ifdef XFree86LOADER
>
> Hmm, didn't you want to remove XFree86LOADER completely?

Ah. Good catch!

Mike
-- 

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
mobile: +49 (1520) 1976 148
landline: +49 (4354) 8390 139

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

2016-11-02 17:00 UTC, sunweaver commented on nx-X11/programs/Xserver/randr/randr.c
> +
> please remove leftover empty lines (in randr.c)

done

2016-11-02 17:01 UTC, sunweaver commented on nx-X11/programs/Xserver/fb/fb24_32.c
>  #ifdef XFree86LOADER
> forgot to remove XFree86LOADER? (in fb24_32.c)

yep. removed now.

2016-11-02 17:02 UTC, sunweaver commented on nx-X11/programs/Xserver/GL/glx/glxscreens.c
> +
glxscreens.c is not part of this PR anymore

2016-11-02 17:03 UTC, sunweaver commented on nx-X11/programs/Xserver/Xext/Imakefile
> -
done with rebasing...

2016-11-02 17:04 UTC, sunweaver commented on nx-X11/programs/Xserver/GL/glx/glxscreens.c
> +
glxscreens.c is still _part_ of this PR... empty line remove now.

2016-11-02 17:06 UTC, sunweaver commented
@uli42: PR #251 is ready for a second interation. Thanks!

2016-11-04 10:45 UTC, sunweaver commented
@uli42: Did you have any time to look into PR #251 once more?

2016-11-04 10:56 UTC, uli42 requested changes
Have a look at `extras/Mesa/src/mesa/main/imports.c`, I can see lots of `XFree86LOADER` stuff there

2016-11-04 10:56 UTC, uli42 commented on nx-X11/programs/Xserver/Xext/shm.c
> +
why that extra line?

2016-11-04 10:56 UTC, uli42 commented on nx-X11/programs/Xserver/GL/glx/glxscreens.c
> -#ifdef IN_MODULE
there are lots of other IN_MODULE checks all over the code. The should go, too!

2016-11-17 21:11 UTC, sunweaver commented
@uli42: I have reworked this PR, please take a second look, make comments and if ok, please approve. Otherwise specify change requests. Thanks!

2016-12-03 21:09 UTC, uli42 approved these changes
Looks good now.

2016-12-04 20:14 UTC, merged