Imakefile cleanup: Delete all ancient Vcs comments stemming from SVN …
ArcticaProject/nx-libs pull request #254
Opened 2016-10-29 13:33 UTC by sunweaver

…times of X.org and XFree86.

 Fixes ArcticaProject/nx-libs#250.

2016-10-30 20:29 UTC, sunweaver commented
@uli42: please review #254. Thanks.

2016-10-30 21:02 UTC, uli42 requested changes

2016-10-30 21:02 UTC, uli42 commented on nx-X11/config/cf/X11.tmpl
> +XCOMM ----------------------------------------------------------------------
remove single empty XCOMMs?

2016-10-30 22:44 UTC, sunweaver commented on nx-X11/config/cf/X11.tmpl
> +XCOMM ----------------------------------------------------------------------
I am not getting your point here? What do you suggest?

2016-10-31 01:35 UTC, uli42 commented on nx-X11/config/cf/X11.tmpl
> +XCOMM ----------------------------------------------------------------------
forget it, I was mislead by the github diff display. PR ist ok for me

2016-10-31 01:35 UTC, uli42 approved these changes

2016-10-31 11:47 UTC, sunweaver commented
Closed by https://github.com/ArcticaProject/nx-libs/commit/4c59a3c58b873440573cd29eee0ead6f7dd78fcf

2016-10-31 11:47 UTC, closed without merging