Pr/unused files
ArcticaProject/nx-libs pull request #267
Opened 2016-10-30 20:54 UTC by uli42

Drop a lot of files, this is related to #256. It removes the files we agreed can go. 

Also drops DoLoadableServer support.

2016-10-30 22:50 UTC, sunweaver requested changes
Please keep ffs.c (dix/) for now. The rest looks good.

2016-10-30 22:50 UTC, sunweaver commented on nx-X11/programs/Xserver/dix/ffs.c
> -}
Skip this commit for now in this PR. This affects the Win32 support discussion. This file should be removed, once we drop Win32 support.

2016-10-30 23:04 UTC, sunweaver commented
@uli42: please rebase #267's PR branch against latest 3.6.x, as well...

2016-10-31 02:48 UTC, uli42 commented on nx-X11/programs/Xserver/dix/ffs.c
> -}
done

2016-10-31 11:49 UTC, sunweaver commented
@uli42: You re-pushed last night, but the branch still had one conflict. Please rebase against latest 3.6.x again and make sure the PR branch for #267 can be merged cleanly on top of 3.6.x.

2016-10-31 14:30 UTC, uli42 commented
Unfortunately this rebase is not straight forward, I will need some time for it. Probably not today, sorry.

2016-11-01 21:08 UTC, sunweaver commented
@uli42: I am currently rebasing this branch, so you can fetch my rebased branch and force-push to your PR branch again. Sorry for the mess.

2016-11-01 21:14 UTC, sunweaver commented
@uli42: obtain my rebased branch with these commands:

```
git remote add gh-sunweaver git@github.com:sunweaver/nx-libs.git
git fetch gh-sunweaver pr/unused_files:sunweaver-pr/unused_files
git branch -m pr/unused_files pr/unused_files.bak
git branch -m sunweaver-pr/unused_files pr/unused_files
```

and then (after checking), force-push to the PR branch again:

```
git push --force <github-uli42-remote> pr/unused_files:pr/unused_files
```

Thanks+Greets,
Mike

2016-11-02 10:13 UTC, uli42 commented
done.

2016-11-02 10:49 UTC, sunweaver approved these changes

2016-11-02 11:03 UTC, sunweaver requested changes
@uli42: I have disapproved this PR again, as I get FTBFS at various locations.

Also, I don't think dropping damage.c is a really good idea, because it gets included in Xserver/hw/nxagent/NXdamage.c (yes, the .c file gets included).

I can continue looking at this PR and will investigate later today/tomorrow.

2016-11-02 11:24 UTC, sunweaver commented
Also, you have moved damage.h to Xserver/include. In X.org, this file is still in miext/damage/... Moving it back there.

2016-11-02 11:37 UTC, sunweaver commented
I have fixed the FTBFS issues and pushed to pr/unused_files on https://github.com/sunweaver/nx-libs again. Please check once more and force-push to this PR's update branch. Thanks.

2016-11-02 16:20 UTC, uli42 commented
Sorry, I missed that damage.c include somehow. I am ok with that change.

I am running out of time for now, so you can merge that from your
tree, I don't see why you'd need to use my PR.

One thing I noticed, though: commit
99b54bceaa3a6fc3d2133e08ff015c594fdff013 contains a now historical
conflicts message. That one should vanish.


On Wed, Nov 2, 2016 at 12:37 PM, Mike Gabriel <notifications@github.com> wrote:
> I have fixed the FTBFS issues and pushed to pr/unused_files on
> https://github.com/sunweaver/nx-libs again. Please check once more and
> force-push to this PR's update branch. Thanks.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.

2016-11-02 16:57 UTC, sunweaver commented
Obsoleted by 1d1d1fc2199672c722dd75cefe8389268bfbbad3. Closing.

2016-11-02 16:57 UTC, closed without merging