Pr/upgrade xtrans
ArcticaProject/nx-libs pull request #268
Opened 2016-10-31 02:44 UTC by uli42

Lift xtrans to current head.

2016-10-31 11:20 UTC, sunweaver requested changes
I left two comments plus this general request: In your commit messages, please don't reference X.org as "upstream", but as "X.org" or "X.org upstream". Thanks.

And another general question: Shouldn't we drop AIX, OS2 and other archs completely? I understand that this PR only tackles Xtrans, but we should actually let another clean-up PR follow-up that removes the old archs completely. Right? I will merge this PR nonetheless and add an issue for each arch that we want to remove.

The rest looks good. Well done!

2016-10-31 11:20 UTC, sunweaver commented on nx-X11/lib/xtrans/Xtrans.c
@uli42: please add Backported-to-NX-by: for 79104451e3a0bf77ac239341d68e39162f7bb975.

2016-10-31 11:20 UTC, sunweaver commented on nx-X11/lib/xtrans/Xtransint.h
> -
@uli42: please add Backported-to-NX-by: for f8cfe723e45834209d70ab0390f3fd782d6872fa.

2016-11-02 10:54 UTC, uli42 commented on nx-X11/lib/xtrans/Xtransint.h
> -
done

2016-11-02 10:55 UTC, uli42 commented
I have done the requested changes (+ whitespace fixes). And I agree on removal of these archs. Please open issues for that.

2016-11-02 18:49 UTC, sunweaver approved these changes

2016-11-02 18:53 UTC, sunweaver commented
Rebased and merged as 107e72b038bc76953dc97d4ea655c9bde10e5865. Thus, closing.

2016-11-02 18:53 UTC, closed without merging