LibX11: drop unused xlibi18n
ArcticaProject/nx-libs pull request #279
Opened 2016-11-04 08:56 UTC by uli42

remove support for _loadable_ `xlibli18n`

As i18n is used by the application and we are the ones controlling the application (nxagent) it might also be possible to drop that i18n stuff completely! I have not investigated further, though.

2016-11-09 15:05 UTC, sunweaver requested changes
I found two more occurences of xlibi18n (grep -i). Please handle those via this PR, too.

Except from that, this PR is fine.

2016-11-09 15:05 UTC, sunweaver commented on nx-X11/config/cf/X11.tmpl
> -#endif
I just grepped for more places where xlibi18n gets mentioned:

```
 [mike@minobo nx-X11 (uli42-pr/remove_xlibi18n)]$ grep -ri xlibi18n *
config/cf/lnxLib.tmpl:#define SharedXlibi18nReqs $(LDPRELIB) $(XONLYLIB)
config/cf/X11.tmpl: * This disables XLOCALEDIR.  Set it if you're using BuildLoadableXlibI18n,
```

2016-11-09 15:05 UTC, sunweaver commented on nx-X11/config/cf/X11.tmpl
> -#endif
Please amend those and include in this commit, too.

2016-11-17 16:20 UTC, uli42 commented on nx-X11/config/cf/X11.tmpl
> -#endif
rebased and added the two requested changes

2016-11-17 19:44 UTC, sunweaver approved these changes

2016-11-17 19:52 UTC, merged