add .gitignore files
ArcticaProject/nx-libs pull request #280
Opened 2016-11-04 10:23 UTC by uli42

SSIA

2016-11-04 10:45 UTC, sunweaver requested changes
Please consider my comments, I will merge this once we have xlibi18n removed.

2016-11-04 10:45 UTC, sunweaver commented on nx-X11/lib/X11/.gitignore
> +xlibi18n/om/generic/omXChar.c
This can go away anyway, after #279 has been merged...

2016-11-04 10:45 UTC, sunweaver commented on nx-X11/.gitignore
> +exports/
What about .build-exports?

2016-11-04 10:48 UTC, uli42 commented on nx-X11/.gitignore
> +exports/
I neither know nor have that!?

2016-11-04 10:48 UTC, uli42 commented on nx-X11/lib/X11/.gitignore
> +xlibi18n/om/generic/omXChar.c
sure

2016-11-04 12:43 UTC, sunweaver commented
Hi Uli,

On  Fr 04 Nov 2016 11:48:43 CET, Ulrich Sibiller wrote:

> uli42 commented on this pull request.
>
>
>
>> @@ -0,0 +1,4 @@
> +Makefile
> +Makefile.bak
> +xmakefile
> +exports/
>
> I neither know nor have that!?

the nx-X11/.build-exports gets created when running make install on  
our main Makefile. It gets called whenever you build the nx-libs code  
with dpkg-buildpackage.

Mike
-- 

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
mobile: +49 (1520) 1976 148
landline: +49 (4354) 8390 139

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

2016-11-04 20:57 UTC, uli42 commented
OK, have added `.build-exports/`

2016-11-17 16:21 UTC, uli42 commented
rebased, but should be adapted as soon as #279 has been merged

2016-11-17 19:53 UTC, sunweaver commented
@uli42: #279  has been merged, please make this PR ready for merging it finally. Thanks.

2016-11-17 22:54 UTC, uli42 commented
rebased + removed xlibi18n stuff from .gitignore

2016-11-17 23:03 UTC, sunweaver approved these changes

2016-11-17 23:07 UTC, merged