Xserver: hard-code rgb colors
ArcticaProject/nx-libs pull request #319
Opened 2017-02-06 16:36 UTC by sunweaver

Immitate what X.org has done a while ago. Drop rgb in text fromat or DBM format and simply hard-code it in Xserver/os/oscolor.c.

2017-02-18 09:53 UTC, Ionic commented
Is this one for me?

2017-02-18 11:42 UTC, sunweaver commented
Yes, go ahead.

On Sat Feb 18 10:53:32 2017 GMT+0100, Mihai Moldovan wrote:
> Is this one for me? 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.￼
>

-- 
Sent from my Fairphone (running Sailfish OS)...

2017-02-22 07:21 UTC, Ionic requested changes
Everything else looks okay. The warning... is probably just gcc being too helpful. One could probably split the large arrays up and concat them together at run time, but if compilers are handling it just fine it's probably better to not add such a quirk. That's my interpretation of why upstream didn't do it in the first place.

2017-02-22 07:21 UTC, Ionic commented on nx-X11/programs/Xserver/os/Imakefile
>  		  -I$(SERVERSRC)/Xext -I$(SERVERSRC)/render \
`$(RGB_DEFINES)` three lines above this one.

2017-02-22 07:21 UTC, Ionic commented on nx-libs.spec
> -%config(noreplace) %{_sysconfdir}/nxagent/rgb
@opoplawski is that enough to drop config files? I searched around, but it seems that RPM has no special concept of config file deprecation. Will it do the right thing automatically, or just leave the file around, even if unmodified?

2017-02-22 07:21 UTC, Ionic commented on nx-X11/programs/Xserver/os/oscolor.c
> +#include <X11/keysym.h>
Why do we need that? Looks misplaced, keysyms shouldn't be used in `oscolor.c` at all.

2017-02-22 16:21 UTC, opoplawski commented on nx-libs.spec
> -%config(noreplace) %{_sysconfdir}/nxagent/rgb
It will do the right thing - remove the file if unmodified - keep a copy as rgb.rpmsave if it was.

2017-02-24 05:37 UTC, Ionic commented on nx-libs.spec
> -%config(noreplace) %{_sysconfdir}/nxagent/rgb
Okay, thanks!

2017-02-26 17:37 UTC, sunweaver commented on nx-X11/programs/Xserver/os/oscolor.c
> +#include <X11/keysym.h>
This is true. I "blindly" copied over X.org's oscolor.c. This really feels like an unneeded include. Dropping it (and diverting from X.org).

2017-02-26 17:45 UTC, sunweaver commented
@Ionic: requested changes worked-in and rebased against 3.6.x branch. Please take another look and merge.

2017-02-26 17:46 UTC, sunweaver commented on nx-X11/programs/Xserver/os/Imakefile
>  		  -I$(SERVERSRC)/Xext -I$(SERVERSRC)/render \
>  $(RGB_DEFINES) three lines above this one.

Yep. Removed now.

2017-02-27 03:08 UTC, Ionic approved these changes

2017-02-27 03:09 UTC, merged