xkb: Allow NULL as rulesFile in XkbSetRulesDflts.
ArcticaProject/nx-libs pull request #372
Opened 2017-03-02 21:08 UTC by uli42

If no rules file is given, simply re-use the previous one. If no RF is given
the first time this function is called, use the built-in default.
This includes fixing the built-in default to something that actually exists.

Signed-off-by: Peter Hutterer <peter.hutterer@redhat.com>
Backported-to-NX-by: Ulrich Sibiller <uli42@gmx.de>

see #371

2017-03-03 09:05 UTC, sunweaver requested changes
@uli42: the backported code itself is ok, but please clearly reference the original X.org server commit in the nx-libs commit message, e.g. like in https://github.com/ArcticaProject/nx-libs/pull/334/commits/04a791f028b8731f729cddbbcfcec488bd51fcdc

2017-03-03 20:48 UTC, sunweaver commented
@uli42: ping

2017-03-03 20:51 UTC, uli42 commented
I have doen it the same way I did it with all the libX11 backports. Peter Hutterer appears as author of this now.

2017-03-03 21:46 UTC, sunweaver commented
Please rebase against latest 3.6.x branch.

2017-03-03 22:01 UTC, uli42 commented
rebased

2017-03-04 07:04 UTC, Ionic commented
You have to really rebase again - the new code uses `_XkbDupString()` which you removed previously.

2017-03-07 21:40 UTC, Ionic commented
Still needs a rebase.

2017-03-07 22:05 UTC, uli42 commented
is long done! Please re-check!

On Tue, Mar 7, 2017 at 10:40 PM, Mihai Moldovan
<notifications@github.com> wrote:
> Still needs a rebase.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.

2017-03-07 22:09 UTC, Ionic commented
You're still using `_XkbDupString()` in this PR's code. Are you sure you pushed your changes correctly?

2017-03-07 22:26 UTC, uli42 commented
On Tue, Mar 7, 2017 at 11:09 PM, Mihai Moldovan
<notifications@github.com> wrote:
>
> You're still using _XkbDupString() in this PR's code. Are you sure you pushed your changes correctly?

Ah, right, _now_ it should fit

2017-03-07 22:29 UTC, Ionic approved these changes

2017-03-07 22:31 UTC, Ionic commented
Can you please rebase *again* against current `3.6.x`? This is out of date since I merged your other PR. I could rebase it myself, but Github won't recognize it as a PR merge if I did that...

2017-03-07 22:52 UTC, uli42 commented
done

On Tue, Mar 7, 2017 at 11:31 PM, Mihai Moldovan <notifications@github.com>
wrote:

> Can you please rebase *again* against current 3.6.x? This is out of date
> since I merged your other PR. I could rebase it myself, but Github won't
> recognize it as a PR merge if I did that...
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ArcticaProject/nx-libs/pull/372#issuecomment-284881999>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AGBw5CPo9CygP3B8SHRHailrIqkxQxG3ks5rjdregaJpZM4MRiFl>
> .
>

2017-03-07 22:54 UTC, merged