Pr/misc cherries
ArcticaProject/nx-libs pull request #378
Opened 2017-03-03 21:09 UTC by uli42

These are some fixes that I have done back in December. Some of them are pretty obvious an can be cherry-picked, I'd say.

2017-03-04 07:11 UTC, Ionic commented on nx-X11/programs/Xserver/hw/nxagent/Args.c
>        return;
Hum, doesn't that mean that selecting did nothing so far? Good fix.

2017-03-04 07:20 UTC, Ionic commented on nx-X11/programs/Xserver/hw/nxagent/Rootless.c
> +    free(toplevel);
Making a note here, `toplevel` could be ported to use `allocarray()`.

2017-03-04 07:28 UTC, Ionic commented on nx-X11/programs/Xserver/hw/nxagent/Rootless.c
> +    /* FIXME: is it okay here to ignore malloc fails? */
Well given the code is only doing something when `malloc` succeeded... probably okay... If `export` isn't true, the function won't do much later on.

2017-03-04 07:37 UTC, Ionic commented on nx-X11/programs/Xserver/hw/nxagent/Rootless.c
> +      #ifdef WARNING
Maybe convert everything here to use `allocarray` as well?

2017-03-04 07:43 UTC, Ionic commented on nx-X11/programs/Xserver/hw/nxagent/Rootless.c
> +    fprintf(stderr, "nxagentRootlessRestack: [%p]\n", toplevel[i]);
I'd use `"%s: ...", __func__, ...` in this commit and especially in all new code.

2017-03-04 08:10 UTC, Ionic requested changes

2017-03-04 08:10 UTC, Ionic commented on nx-X11/programs/Xserver/hw/nxagent/Window.c
> -  int flexibility = *(int *) p0;
NAK, don't remove that.

Add `(void) flexibility;` instead. Otherwise we will never know what this `p0` argument is supposed to be in the future.

2017-03-04 08:15 UTC, uli42 commented
Well, we could add an according comment...

Vom Smartphone gesendet.

----- Ursprüngliche Nachricht -----
Von: "Mihai Moldovan" <notifications@github.com>
Gesendet: ‎04.‎03.‎2017 09:10
An: "ArcticaProject/nx-libs" <nx-libs@noreply.github.com>
Cc: "Ulrich Sibiller" <uli42@gmx.de>; "Author" <author@noreply.github.com>
Betreff: Re: [ArcticaProject/nx-libs] Pr/misc cherries (#378)

@Ionic requested changes on this pull request.



In nx-X11/programs/Xserver/hw/nxagent/Window.c:
> @@ -2684,8 +2684,6 @@ void nxagentDisconnectWindow(void * p0, XID x1, void * p2)
 
 Bool nxagentReconnectAllWindows(void *p0)
 {
-  int flexibility = *(int *) p0;
NAK, don't remove that.
Add (void) flexibility; instead. Otherwise we will never know what this p0 argument is supposed to be in the future.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.

2017-03-04 08:21 UTC, Ionic commented
Yeah, but comments are more easily and inadvertently removed. An unused stack variable won't kill us - and the compiler likely optimizes it out anyway.

2017-03-04 08:26 UTC, uli42 commented
Hmm. What's the state of the flexibility stuff. I thought it is
finished? What is going to come here in future?  Aaannd: shouldn't we
remove p0 until we really need it?

On Sat, Mar 4, 2017 at 9:21 AM, Mihai Moldovan <notifications@github.com> wrote:
> Yeah, but comments are more easily and inadvertently removed. An unused
> stack variable won't kill us - and the compiler likely optimizes it out
> anyway.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

2017-03-04 08:31 UTC, Ionic commented
Hm, good point, that's long done. Code can get a value via `nxagentOption(ReconnectTolerance)`, so there's probably no need to even keep this argument around.

2017-03-04 08:34 UTC, Ionic commented
I think the original idea in NX code was to provide different values to each function - but that was never actually used.

It wasn't a terrible idea to allow stricter checks for, say, depth and less strict ones for Pixmaps, but given that was never used, we could do away with it altogether and just re-fetch the value on demand if we ever want to make functions more dynamic in their handling.

2017-03-04 08:36 UTC, uli42 commented
ack

2017-03-04 15:21 UTC, uli42 commented on nx-X11/programs/Xserver/hw/nxagent/Args.c
>        return;
I am not sure when exactly that code is active, But it definitely looked wrong ;-)

2017-03-04 15:22 UTC, uli42 commented on nx-X11/programs/Xserver/hw/nxagent/Rootless.c
> +    free(toplevel);
there are _many_ places all over the code...

2017-03-07 21:39 UTC, Ionic commented
How about removing the `void *p0` parameter, then? Currently it would be unused and you're exchanging a compiler warning (`flexibility unused` for another one `argument unused`.)

2017-03-08 13:06 UTC, sunweaver commented
@uli42: @Ionic: let's get this PR in first, and then I revisit #333.

2017-03-08 13:08 UTC, sunweaver commented
@uli42: one reviewer on this PR is enough, please finish this up with Ionic. It feels like this should be the next PR to get merged, right?

2017-03-09 20:23 UTC, uli42 commented on nx-X11/programs/Xserver/hw/nxagent/Rootless.c
> +      #ifdef WARNING
I don't want to integrate allocarray into this pr.

2017-03-09 20:24 UTC, uli42 commented on nx-X11/programs/Xserver/hw/nxagent/Rootless.c
> +    fprintf(stderr, "nxagentRootlessRestack: [%p]\n", toplevel[i]);
Well, there are about 100000 locations all over the place where this could be done. But not in this commit.

2017-03-09 20:26 UTC, uli42 commented
I will rebase this and take out the changes regarding flexibility. Cleaning up there is way more than just removing this variable and p0, so I will open a new issue for that.

2017-03-09 20:33 UTC, uli42 commented
this is basically ready to merge. But as I originally had thought of this a a collection of cherrypicks the question is if the name of the branch should stay in case of a complete merge.

2017-03-10 07:30 UTC, Ionic commented on nx-X11/programs/Xserver/hw/nxagent/Rootless.c
> +    fprintf(stderr, "nxagentRootlessRestack: [%p]\n", toplevel[i]);
Just thought it would make sense if you're changing the lines to include the function anyway.

2017-03-10 07:30 UTC, Ionic commented on nx-X11/programs/Xserver/hw/nxagent/Rootless.c
> +      #ifdef WARNING
I didn't mean in this PR, that was a general comment.

2017-03-10 07:34 UTC, Ionic commented
It doesn't really make sense to cherry-pick single commits. There also isn't one specific topic all commits would fit under... if you can find a better name, rename the branch (although I'm not sure if GH supports that), otherwise I guess it's fine the way it is?

2017-03-10 07:34 UTC, Ionic approved these changes

2017-03-10 19:20 UTC, merged