Backport CVE-2017-2624 (timingsafe_memcmp)
ArcticaProject/nx-libs pull request #380
Opened 2017-03-03 21:57 UTC by uli42

Fixes ArcticaProject/nx-libs#365

These two commits:

   commit 5c44169caed811e59a65ba346de1cadb46d266ec
   Author: Adam Jackson <ajax@redhat.com>
   Date:   Thu Mar 2 17:20:30 2017 -0500

       os: Squash missing declaration warning for timingsafe_memcmp

       timingsafe_memcmp.c:21:1: warning: no previous prototype for ‘timingsafe_memcmp’ [-Wmissing-prototypes]
        timingsafe_memcmp(const void *b1, const void *b2, size_t len)

       Signed-off-by: Adam Jackson <ajax@redhat.com>

   commit d7ac755f0b618eb1259d93c8a16ec6e39a18627c
   Author: Matthieu Herrb <matthieu@herrb.eu>
   Date:   Tue Feb 28 19:18:25 2017 +0100

       Use timingsafe_memcmp() to compare MIT-MAGIC-COOKIES CVE-2017-2624

       Provide the function definition for systems that don't have it.

       Signed-off-by: Matthieu Herrb <matthieu@herrb.eu>

2017-03-04 08:19 UTC, Ionic requested changes

2017-03-04 08:19 UTC, Ionic commented on nx-X11/programs/Xserver/include/os.h
> +#ifndef HAVE_TIMINGSAFE_MEMCMP
We probably also need changes to Imake, given that for instance `OpenBSD` does have a `timingsafe_memcmp` function.

See `nx-X11/config/cf/Imake.tmpl` and `nx-X11/programs/Xserver/os/Imakefile` and look for `strlcat` for how that was done.

2017-03-04 15:12 UTC, uli42 commented on nx-X11/programs/Xserver/include/os.h
> +#ifndef HAVE_TIMINGSAFE_MEMCMP
done. minus library handling. That should be done by someone who has such a system for building.

2017-03-07 21:32 UTC, Ionic approved these changes

2017-03-07 21:36 UTC, merged