Pr/cleanup keystroke
ArcticaProject/nx-libs pull request #392
Opened 2017-03-11 08:44 UTC by uli42

some improvements to keystroke handling. 

Before the code did not accept keystrokes that did not match a Symbol (e.g. when the config file did not define a key but modifiers only for a keystroke). This code accepts it to allow for modifier-only keystrokes. But this does not work properly because of X11 limitations so this will probably change again.

2017-03-11 12:43 UTC, uli42 commented
I have updated this PR to keep the original functionality. modifier-only shortcuts will not work here!

2017-03-13 13:58 UTC, sunweaver requested changes
@uli42: I added some comments / requests. Please check, revisit and give feedback. Thanks.

2017-03-13 13:58 UTC, sunweaver commented on nx-X11/programs/Xserver/hw/nxagent/Keystroke.c
> +  /* FIXME: we do not want to have x2go references int the code */
typo: s/int/in/

And I partially disagree here. We have the X2Go logo hard-coded into nxagent, too. Having hard-code X2Go related code section was a pre-requisite for merging the former x2goagent fork with the original nxagent code base.

2017-03-13 13:58 UTC, sunweaver commented on nx-X11/programs/Xserver/hw/nxagent/Keystroke.c
> +  nxagentKeystrokeFileParsed = True;
Don't set this to true, if the parsing has not happened so far.

It actually should only be set to true, if the parsing of one of the potential files has _really_ been successful.

2017-03-13 13:58 UTC, sunweaver commented on nx-X11/programs/Xserver/hw/nxagent/Keystroke.c
> +  nxagentKeystrokeFileParsed = True;
Getting the code design now after reading more of the code context. The nxagentKeystrokeFileParsed is actually more a Boolean for nxagentKeystrokeFileParsingAttempted. It is saying nothing about its success, only that it happened.

We should add a comment about this near the nxagentKeystrokeFileParsed = True assignment, I'd say.

2017-03-13 13:58 UTC, sunweaver commented on nx-X11/programs/Xserver/hw/nxagent/Keystroke.c
> +     not at first keypress! */
So why not move it over to Init.c?

2017-03-13 15:11 UTC, sunweaver commented
Hi Uli,

On  Sa 11 Mär 2017 09:44:35 CET, Ulrich Sibiller wrote:

> some improvements to keystroke handling.
>
> Before the code did not accept keystrokes that did not match a  
> Symbol (e.g. when the config file did not define a key but modifiers  
> only for a keystroke). This code accepts it to allow for  
> modifier-only keystrokes. But this does not work properly because of  
> X11 limitations so this will probably change again.
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/ArcticaProject/nx-libs/pull/392
>
> -- Commit Summary --
>
>   * Keystroke.c: use Bool type where appropriate
>   * Keystroke.c: rework read_binding_from_xmlnode()
>   * Keystroke.c: fix code formatting, add FIXME
>   * Keystroke.c: simplify nxagentCheckSpecialKeystroke
>   * Keystroke.c: handle parsing state in parse_keystroke_file()
>   * Keystroke.c: reorder parse_keystroke_file
>   * Keystroke.c: Boolify nxagentCheckSpecialKeystroke
>   * Keystroke.c: Boolify read_binding_from_xmlnode
>   * Keystroke.c: use symbols instead of integers
>   * Keystroke.c: Simplify read_binding_from_xmlnode
>   * Keystroke.c: add another FIXME
>   * Keystroke.c: init struct
>   * Keystroke.c: improve TEST output
>   * Keystroke.c: print keystroke name in TEST mode
>   * Keystroke.c: arrange switch_all_screens and fullscreen close together
>
> -- File Changes --
>
>     M etc/keystrokes.cfg (2)
>     M nx-X11/programs/Xserver/hw/nxagent/Keystroke.c (264)
>     M nx-X11/programs/Xserver/hw/nxagent/Keystroke.h (32)
>
> -- Patch Links --
>
> https://github.com/ArcticaProject/nx-libs/pull/392.patch
> https://github.com/ArcticaProject/nx-libs/pull/392.diff

This PR also introduces a compiler warning, I think. Haven't seen it so far...

```
Keystroke.c: In function ‘parse_keystroke_file’:
Keystroke.c:390:15: warning: passing argument 1 of ‘fprintf’ from  
incompatible pointer type
        fprintf("XML parsing for %s failed\n", filename);
                ^
In file included from ../../include/misc.h:198:0,
                  from ../../include/screenint.h:51,
                  from Keystroke.c:29:
/usr/include/stdio.h:356:12: note: expected ‘struct FILE * restrict’  
but argument is of type ‘char *’
  extern int fprintf (FILE *__restrict __stream,
             ^
```
-- 

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
mobile: +49 (1520) 1976 148
landline: +49 (4354) 8390 139

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

2017-03-13 15:25 UTC, Ionic commented
Yeah, this totally won't work. Either `fprintf(stderr, ...)` or `printf(...)`.

2017-03-13 19:57 UTC, uli42 commented on nx-X11/programs/Xserver/hw/nxagent/Keystroke.c
> +  /* FIXME: we do not want to have x2go references int the code */
OK, I thought we wanted to get rid of that completely. Dropping that comment for now.

2017-03-13 21:21 UTC, uli42 commented
I have done (or dropped) the requested changes and added some more commits. Please review once more.

2017-03-13 22:06 UTC, sunweaver approved these changes
One last question (about the removed if clause). Otherwise approved.

2017-03-13 22:06 UTC, sunweaver commented on nx-X11/programs/Xserver/hw/nxagent/Keystroke.c
> -
Why did you remove the above if clause here? Did you do it intentionally? Or is it an editing artifact?

2017-03-13 22:08 UTC, merged

2017-03-14 08:18 UTC, uli42 commented on nx-X11/programs/Xserver/hw/nxagent/Keystroke.c
> -
I am pretty sure it was me who added that code (copy from some lines below), but it is not neccessary. I had added it to allow for "key=0" in my fruitless attempts to implement modifier-only keystrokes.