Mesa subtree: Add quilt based patch system for bundled Mesa.
ArcticaProject/nx-libs pull request #409
Opened 2017-03-24 08:07 UTC by sunweaver

Explanation: The Mesa subtree is a pulled-in (bundled) Mesa 6.4.1. We see many compiler warnings that should get amended, may it only be for the readability of the build logs.

Furthermore, the CreatePixmap() ABI changed in X.org, too. A backport is pending on my local working copy. The CreatePixmap() ABI change will also require a tiny adaptation in Mesa as we ship it.

Later on, the plan is to pull-in Mesa (version 6.4.1 for now, later on possibly newer versions) as a git subtree or submodule. Again, then we won't have our patches for Mesa in the Git log somewhere. The cleaner approach for now is to maintain a separate Mesa-for-NX-patchset IMHO.

This PR provides the foundation for this. The patch system for Mesa will use quilt.

2017-03-24 08:08 UTC, sunweaver commented
@Ionic: can you take a quick look at #409? Thanks.

2017-03-26 07:33 UTC, Ionic requested changes

2017-03-26 07:33 UTC, Ionic commented on mesa-quilt
> +d=. ; while [ ! -d $d/nx-X11/extras -a `readlink -e $d` != / ]; do d=$d/..; done
I'd use `[ ! -d "$d/nx-X11/extras" ] && [ "$(readlink -e "$d")" != "/" ]` here... and generally more quoting in the whole file.

2017-03-27 14:18 UTC, sunweaver commented
@Ionic: I sort of over-quoted the mesa-quilt script now. I guess, this is better now. Please look again. Thanks!

2017-03-30 08:10 UTC, Ionic requested changes

2017-03-30 08:10 UTC, Ionic commented on mesa-quilt
> +d=. ; while [ ! -d "$d/nx-X11/extras" ] && [ "$(readlink -e \"$d\")" != "/" ]; do d="$d/.."; done
Quoting within `$()` is special. You do not need to escape quote characters, which makes working with it much easier.

```bash
[ "$(readlink -e "$d")" != "/" ]
```

2017-03-30 08:10 UTC, Ionic commented on mesa-quilt
> +quilt $@
Quoting `$@` here is important so that the shell doesn't perform automatic word splitting when it shouldn't. Don't leave that out.

2017-04-03 19:18 UTC, sunweaver commented
@Ionic: ok. Next iteration.

2017-04-06 10:16 UTC, Ionic approved these changes

2017-04-06 10:19 UTC, merged