xserver: remove index from CloseScreen (API/ABI breakage)
ArcticaProject/nx-libs pull request #411
Opened 2017-03-24 08:17 UTC by sunweaver

Extracted from X.org bulk commit:

 commit 1f0e8bd5eb1a5539689cfc4f5a6b86b530907ec5
 Author: Dave Airlie <airlied@redhat.com>
 Date:   Tue Jun 5 13:22:18 2012 +0100

    api: rework the X server driver API to avoid global arrays.

    This is a squash merge containing all the API changes, as
    well as the video ABI bump.

    Its been squashed to make bisection easier.

    Full patch log below:

    [...]

    commit 06729dbbc804a20242e6499f446acb5d94023c3c
    Author: Dave Airlie <airlied@gmail.com>
    Date:   Tue Apr 10 14:04:59 2012 +0100

        xserver: remove index from CloseScreen (API/ABI breakage)

        This drops the index from the CloseScreen callback,
        its always been useless really, since the pScreen contains it.

        Reviewed-by: Alan Coopersmith <alan.coopersmith@oracle.com>
        Acked-by: Aaron Plattner <aplattner@nvidia.com>
        Reviewed-by: Adam Jackson <ajax@redhat.com>
        Signed-off-by: Dave Airlie <airlied@redhat.com>

2017-03-24 08:17 UTC, sunweaver commented
@Ionic: and another one for you... (#411).

2017-04-10 10:54 UTC, Ionic commented
Turns out I haven't actually backported this but worked around the change in my branch, so your backport is actually much appreciated. Looking into it.

2017-04-10 11:21 UTC, Ionic requested changes

2017-04-10 11:21 UTC, Ionic commented on nx-X11/programs/Xserver/render/animcur.c
> +    if (screenInfo.numScreens == 0)
Should this really be `0` or rather `1`? Given that this is a length, the latter would make more sense. I'm not sure though.

2017-04-10 11:21 UTC, Ionic commented on nx-X11/programs/Xserver/xfixes/cursor.c
> +    if (screenInfo.numScreens == 0)
Also here.

2017-04-10 12:54 UTC, sunweaver commented on nx-X11/programs/Xserver/render/animcur.c
> +    if (screenInfo.numScreens == 0)
changed to ```if (screenInfo.numScreens == 1)```, as discussed on IRC.

2017-04-10 12:54 UTC, sunweaver commented on nx-X11/programs/Xserver/xfixes/cursor.c
> +    if (screenInfo.numScreens == 0)
dito.

2017-04-10 12:55 UTC, sunweaver commented
@Ionic: PR branch has been updated.

2017-04-10 13:00 UTC, Ionic approved these changes

2017-04-10 13:02 UTC, merged