nx{comp*,proxy}: Drop install-sh and mkinstalldirs and symlink to gnu…
ArcticaProject/nx-libs pull request #422
Opened 2017-04-11 11:57 UTC by sunweaver

…lib's versions of those script instead before build.

 Fixes ArcticaProject/nx-libs#261

2017-04-13 13:02 UTC, Ionic requested changes

2017-04-13 13:02 UTC, Ionic commented on Makefile
> +	    rm -f nx*/install-sh; \
NAK, this PR is bogus.

We should:
  - be fixing `configure.in`:
    - rename it to `configure.ac`
    - add proper automake dependencies to it
  - use `autoreconf -fvi` as part of roll-tarball.sh to generate the build system for the tarballs (which should automatically install install-sh and mkinstalldirs as symlinks if they don't exist and autoreconf determined that the build system is using automake.)

2017-04-13 13:29 UTC, Ionic commented on Makefile
> +	    rm -f nx*/install-sh; \
`mkinstalldirs` is tricky, we should be using `./install-sh -d` instead, since it's deprecated.

2017-04-25 19:48 UTC, sunweaver commented
Will be obsoleted by PR #446, once it is ready...

2017-04-25 19:48 UTC, closed without merging