Pr/extend manpage
ArcticaProject/nx-libs pull request #431
Opened 2017-04-17 22:12 UTC by uli42

some fixes and improvements for nxagent's manpage

2017-04-19 11:54 UTC, sunweaver requested changes
@uli42: thanks for improving the nxagent man page. I left some comments, please amend.

Please also explain and document your reasoning for the first commit regarding the XlibI18n reverse commit. 

Ideally, the man page commits would be in this PR and the reverse commit for XlibI18n in a second PR.

2017-04-19 11:54 UTC, sunweaver commented on nx-X11/lib/X11/Imakefile
> +STATICLCDEPSYMSRCS =
@uli42: Why do we want to re-introduce 'XDefaultIMIF.c' and 'XDefaultOMIF.c'??? Not getting the point here. Please comment and improve the commit message, if you are really intending to revert this.

2017-04-19 11:54 UTC, sunweaver commented on nx-X11/programs/Xserver/hw/nxagent/man/nxagent.1
> +If you want to use nxagent as a replacement for xnest or Xephyr you
s/xnest/Xnest/

2017-04-19 11:54 UTC, sunweaver commented on nx-X11/programs/Xserver/hw/nxagent/man/nxagent.1
> +If you want to use nxagent as a replacement for Xnest or Xephyr you
please merge the typo fix into the prev commit...

2017-04-19 12:04 UTC, uli42 commented on nx-X11/lib/X11/Imakefile
> +STATICLCDEPSYMSRCS =
??? Looks like I have done something wrong. This revert belongs to my static stuff: https://github.com/uli42/nx-libs/tree/nxagent_static

I'll update this PR accordingly

2017-04-20 11:55 UTC, uli42 commented
ok, new push without the wrong commit

2017-04-20 12:05 UTC, sunweaver approved these changes

2017-04-20 12:06 UTC, merged