Pr/cmdline
ArcticaProject/nx-libs pull request #484
Opened 2017-07-11 20:40 UTC by uli42

2017-07-12 09:00 UTC, sunweaver requested changes
Hi Uli, I left two minor comments on this PR. Looks basically, good. Please consider my two comments and give feedback, maybe change the code. Then I'll approve and merge.

Mike

2017-07-12 09:00 UTC, sunweaver commented on nx-X11/programs/Xserver/hw/nxagent/Args.c
> +      }
About the commit msg of this commit: it does actually fix #476, right? Why do you use "addresses"?

2017-07-12 09:00 UTC, sunweaver commented on nx-X11/programs/Xserver/hw/nxagent/Args.c
> +      {
In nxcomp/Loop.cpp, we have this check on the DISPLAY var:

```
    else if (strncasecmp(display, "nx/nx,", 6) == 0 ||
                 strncasecmp(display, "nx,", 3) == 0 ||
                     strncasecmp(display, "nx/nx:", 6) == 0 ||
                         strncasecmp(display, "nx:", 3) == 0)
    {
      [...]
    }
```

2017-07-12 09:00 UTC, sunweaver commented on nx-X11/programs/Xserver/hw/nxagent/Args.c
> +      {
Maybe you want to improve the above check?

2017-07-12 09:37 UTC, uli42 commented on nx-X11/programs/Xserver/hw/nxagent/Args.c
> +      {
I was thinking about checking for all 4 of these. But I consider most of them as obsolete, nowadays I only see "nx/nx". Also I am not really happy with using nx/nx here at all, it feels like misuse here. Maybe we should simply interpret a `:` at the beginning as marker for a string.

2017-07-12 09:37 UTC, uli42 commented on nx-X11/programs/Xserver/hw/nxagent/Args.c
> +      }
Because it is not really a bug... It does not "repair" something.

2017-07-12 10:26 UTC, sunweaver commented
Hi Uli,

On  Mi 12 Jul 2017 11:37:03 CEST, Ulrich Sibiller wrote:

> uli42 commented on this pull request.
>
>
>
>> @@ -283,7 +283,16 @@ int ddxProcessArgument(int argc, char *argv[], int i)
>
>      if (nxagentOptionFile)
>      {
> -      nxagentProcessOptionsFile();
> +      /* if the "filename" starts with nx/nx treat it
> +	 as an option string */
> +      if (strncasecmp(nxagentOptionFile, "nx/nx", 5) == 0)
> +      {
>
> I was thinking about checking for all 4 of these. But I consider  
> most of them as obsolete, nowadays I only see "nx/nx". Also I am not  
> really happy with using nx/nx here at all, it feels like misuse  
> here. Maybe we should simply interpret a `:` at the beginning as  
> marker for a string.

I'd put all of the options string starters here as shown in  
nxcomp/Loop.cpp PLUS the one we really want. This provides some legacy  
support for people used to fiddling with $DISPLAY and does not really  
hurt either.

You should esp. honour the "nx/nx," check rather than "nx/nx"  
(matching nx/nxfoobar).

Mike
-- 

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
mobile: +49 (1520) 1976 148
landline: +49 (4354) 8390 139

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

2017-07-12 10:28 UTC, sunweaver commented
On  Mi 12 Jul 2017 11:37:37 CEST, Ulrich Sibiller wrote:

> uli42 commented on this pull request.
>
>
>
>> @@ -283,7 +283,16 @@ int ddxProcessArgument(int argc, char *argv[], int i)
>
>      if (nxagentOptionFile)
>      {
> -      nxagentProcessOptionsFile();
> +      /* if the "filename" starts with nx/nx treat it
> +	 as an option string */
> +      if (strncasecmp(nxagentOptionFile, "nx/nx", 5) == 0)
> +      {
> +	nxagentParseOptionString(nxagentOptionFile + 5);
> +      }
> +      else
> +      {
> +	nxagentProcessOptionsFile(nxagentOptionFile);
> +      }
>
> Because it is not really a bug... It does not "repair" something.

Oh right. But this prevents Github from automatically closing the  
issue. Please let's use the phrase:

  Fixes ArcticaProject/<gitrepo>#<no>

everywhere where we want GH to automatically close an issue report. No  
matter, if it closes a bug, brings a new feature or answers a question.

Thanks!
Mike
-- 

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
mobile: +49 (1520) 1976 148
landline: +49 (4354) 8390 139

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

2017-07-17 11:40 UTC, sunweaver commented
@uli42: Can we get this done some time soon? Thanks!

2017-07-17 11:50 UTC, uli42 commented
Will try to do it this evening

2017-07-23 00:23 UTC, uli42 commented
Please check once again

2017-07-24 09:52 UTC, sunweaver requested changes
Nearly there. Two changes requested:

  * move extended "nx/nx," et al. string comparison to second commit.
  * fix commit message in second commit to properly close the referenced issue.

2017-07-24 09:52 UTC, sunweaver commented on nx-X11/programs/Xserver/hw/nxagent/Args.c
> +	nxagentProcessOptionsFile(nxagentOptionsFilename);
Thanks for adding those. However, these changes do not belong into this commit, it seems. Rather into the previous commit. I know this is picky, but I'd like the history to be as clean as possible.

Also: you haven't updated the "addresses <issue>" line the previous commit's commit msg. Please use "Fixes ArcticaProject/nx-libs#<issue>." there.

2017-07-24 21:48 UTC, uli42 commented on nx-X11/programs/Xserver/hw/nxagent/Args.c
> +	nxagentProcessOptionsFile(nxagentOptionsFilename);
This is not picky. I think I have done something wrong while rebasing...

2017-07-24 22:03 UTC, uli42 commented
Better now?

2017-07-25 06:58 UTC, sunweaver approved these changes

2017-07-25 07:21 UTC, merged