nxcomp/configure.ac: Don't rely on pkg-config alone when it comes to …
ArcticaProject/nx-libs pull request #499
Opened 2017-08-03 15:01 UTC by sunweaver

…testing for presence of libjpeg shared lib and header files.

 Especially systems still using the IJG's libjpeg implementation
 are likely to lack the libjpeg.pc file.
 .
 So we add some alternative way of detecting if all libjpeg related
 build-dependencies are in place.

This fixes nx-libs builds on Ubuntu trusty:
https://jenkins.arctica-project.org/job/nx-libs.deb+nightly/target=trusty/272/

2017-08-03 15:03 UTC, sunweaver commented
@Ionic: we should get this one in first... (#499, FTBFS on Ubuntu trusty and other older Linux distros).

2017-08-04 06:40 UTC, Ionic requested changes

2017-08-04 06:40 UTC, Ionic commented on nxcomp/configure.ac
> +AC_PATH_PROG(PKGCONF, pkg-config)
I don't like that...

We should keep using `PKG_CHECK_MODULES(JPEG, libjpeg)` (and actually "convert" this and all the other calls to `PKG_CHECK_MODULES([...], [...])` instead).

`PKG_CHECK_MODULES()` has the following declaration:
> `PKG_CHECK_MODULES(VARIABLE-PREFIX, MODULES, [ACTION-IF-FOUND], [ACTION-IF-NOT-FOUND])`

The default `ACTION-IF-NOT-FOUND` action will break out with an error, but we can also provide a special function to handle that case (i.e., in our case, the code in the `else` branch).

```m4
AC_DEFUN([LIBJPEG_CHECK],[
AC_MSG_CHECKING([for libjpeg shared libary file and headers])
AC_CHECK_LIB([jpeg], [jpeg_destroy_compress],
	[have_jpeg_lib=yes], [have_jpeg_lib=no])
AC_CHECK_HEADERS([jpeglib.h],
	[have_jpeg_headers=yes], [have_jpeg_headers=no])

if test x"$have_jpeg_lib" = "xyes" && test x"$have_jpeg_headers" = "xyes"; then
	AC_MSG_RESULT([yes])
	JPEG_CFLAGS=""
	JPEG_LIBS="-ljpeg"
else
	AC_MSG_RESULT([no])
	AC_MSG_FAILURE([Could not find libjpeg on your system, make sure
the JPEG shared library and header files are installed.])
fi
])

PKG_CHECK_MODULES([JPEG], [libjpeg], [], [LIBJPEG_CHECK])
```

I'd put the `LIBJPEG_CHECK` function in `nx-macros.m4`.

Please test that, though. Both on a system that has pkgconfig files for libjpeg and on a system which doesn't have them. Pay close attention to the output. I don't know if and how nested `AC_MSG_CHECKING`/`AC_MSG_RESULT` work out.

2017-08-06 03:07 UTC, sunweaver commented on nxcomp/configure.ac
> +AC_PATH_PROG(PKGCONF, pkg-config)
@Ionic: wow, this works like sharm. Tested with three occasions:

  * no libjpeg-dev installed at all
  * libjpeg-dev installed (including .pc file)
  * libjpeg-dev installed, but .pc file renamed

2017-08-06 03:08 UTC, sunweaver commented
@Ionic: your turn again...

2017-08-07 07:07 UTC, Ionic commented on nxcomp/configure.ac
> +PKG_CHECK_MODULES(PNG, libpng)
If touching these lines anyway, make that `PKG_CHECK_MODULES([...], [...])` too, please.

2017-08-08 11:54 UTC, sunweaver commented
@Ionic: go ahead, please (#499)

2017-08-09 04:42 UTC, Ionic approved these changes

2017-08-09 04:47 UTC, merged

2017-08-09 04:49 UTC, Ionic commented
With cleanups in 8b88289eea2d9325465fd4517e08118d2affcb7d and 8235925a2c3599a8980ce789e0a79369118727fe.