spec file fixes
ArcticaProject/nx-libs pull request #516
Opened 2017-09-23 08:55 UTC by mikedep333

Multiple fixes to make the RPM .spec file work with the version of nx-libs.

2017-09-25 08:11 UTC, sunweaver approved these changes
LGTM. Anything else needed for this PR or can I merge?

THANKS!
Mike

2017-09-27 14:51 UTC, Ionic requested changes
Some requests for changes, some questions.

2017-09-27 14:51 UTC, Ionic commented on nx-libs.spec
> +%{_libdir}/libNX_X11.la
I'm not sure we want to actually ship `.la` files. Debian and other distributions I know just delete them. Is Fedora/RHEL handling that differently?

2017-09-27 14:51 UTC, Ionic commented on nx-libs.spec
> +%{_libdir}/libXcomp.la
`.la`

2017-09-27 14:51 UTC, Ionic commented on nx-libs.spec
> +%{_libdir}/libXcompshad.la
`.la`

2017-09-27 14:51 UTC, Ionic commented on nx-libs.spec
>  %dir %{_libdir}/nx/bin
Better change this to `%{_libexecdir}` as well, I guess.

2017-09-27 14:51 UTC, Ionic commented on nx-libs.spec
> +%define _libexecdir %{_libdir}/nx/bin
Merge this commit into the previous one, otherwise we'll get needless inconsistencies between commits.

2017-09-27 14:56 UTC, Ionic commented on nx-libs.spec
>  %dir %{_libdir}/nx/bin
More information: according to the [Fedora Packaging Guidelines](https://fedoraproject.org/wiki/Packaging:Guidelines#Packaging_Static_Libraries), `.la` files should be deleted and not shipped - static libraries should be avoided at all costs.

The better handling would probably thus to be deleting these files in the `%install` section like we do in `debian/rules`.

2017-11-04 08:31 UTC, sunweaver commented
@mikedep333: ping on the requested changes for nx-libs PR #516. Thanks!

2017-12-13 23:38 UTC, closed without merging