Backport `asprintf` implementation.
ArcticaProject/nx-libs pull request #592
Opened 2017-12-07 10:24 UTC by Ionic

`asprintf` is not available everywhere. One of such platform is Windows.

Luckily, X.Org has a wrapper for this. We currently use X.Org's implementation of `Xprintf` unconditionally anyway, since NoMachine implemented a workaround for `vsnprintf` returning `-1` on truncation on some platforms (older glibc versions).

This backport should have happened way earlier when we first started using `asprintf`, but I  didn't think of it back then.

2017-12-07 10:37 UTC, sunweaver requested changes
```
11:26 <@sunweaver> Ionic: we have omitted the _X_EXPORT "decorator" (or how they are called) everywhere 
                   else, so far.
11:27 < Ionic> not really
11:27 < Ionic> I've git grepped for it and it turned up in a lot of locations, so why not add it
11:30 <@sunweaver> yep.
11:30 <@sunweaver> ok.
11:32 <@sunweaver> Ionic: would it make sense to do the same wrapping as in X.orgs Xprintf.h?`
11:32 <@sunweaver> http://paste.debian.net/999615/
11:32 <@sunweaver> compared with diff -w
11:32 <@sunweaver> so, as I see it, the diff could be empty.
11:32 <@sunweaver> why not go there?
11:34 < Ionic> hum
11:34  -!- narenas <~Adium@88.12.19.210> has quit (Quit: Leaving.)
11:36 <@sunweaver> same for xprintf.c in Xserver/os.
11:36 <@sunweaver> also, why did you skip +Xvscnprintf()?
11:36 <@sunweaver> that would make the porting complete.
11:36 < Ionic> did I?
11:36 <@sunweaver> http://paste.debian.net/999617/
```

2017-12-07 11:14 UTC, Ionic commented
Merged in changes from global re-intendeation commit and added `(v)scnprintf` backport.

2017-12-10 11:15 UTC, sunweaver approved these changes

2017-12-10 11:19 UTC, sunweaver commented
closed via https://github.com/ArcticaProject/nx-libs/commit/e54e42af93017ba6ab5f18a83e705a8e24ed3906

2017-12-10 11:19 UTC, closed without merging