Pr/saver unvalidated lengths proc screen saver unset attributes
ArcticaProject/nx-libs pull request #672
Opened 2018-03-05 10:14 UTC by sunweaver

Two patches from X.org that are missing in Xserver/Xext/saver.c. One of them addresses a CVE.

2018-03-05 13:35 UTC, uli42 commented
looks good to me

2018-03-05 22:25 UTC, Ionic requested changes
Rejecting while investigation pending.

2018-03-05 22:25 UTC, Ionic commented on nx-X11/programs/Xserver/Xext/saver.c
> -    swapl(&stuff->suspend);
NAK.

X.Org removed this, but as far as I can tell this is actually an oversight/a bug. I'll poke X.Org to find out why they thought that might be a good idea.

2018-03-07 19:44 UTC, sunweaver commented
@Ionic: I have moved the dodgy commit, now only the CVE fix is left. Please merge.

2018-03-07 20:52 UTC, Ionic approved these changes

2018-03-07 20:56 UTC, merged