Pr/small fixes
ArcticaProject/nx-libs pull request #797
Opened 2019-04-29 21:30 UTC by uli42

SSIA

2019-04-30 04:02 UTC, mjtrangoni commented on nx-X11/programs/Xserver/xkb/ddxLoad.c
> +            ErrorF("Warning: Spurious failure reported in Pclose() running 'xkbcomp'.\n");
ddxLoad.c: **fix** spelling.

2019-04-30 07:16 UTC, uli42 commented on nx-X11/programs/Xserver/xkb/ddxLoad.c
> +            ErrorF("Warning: Spurious failure reported in Pclose() running 'xkbcomp'.\n");
d'Oh... Will fix tonight

2019-05-10 14:19 UTC, sunweaver approved these changes
Great. Two minor comments about README.keystrokes. Will fix them before pushing.

2019-05-10 14:19 UTC, sunweaver commented on doc/nxagent/README.keystrokes
> +a dialog informing the user about the taken action. Alls these dialogs
s/Alls/All/

2019-05-10 14:19 UTC, sunweaver commented on doc/nxagent/README.keystrokes
> +  clients. If you want that the clients to see the keystroke you must
``s/If you want that the clients/If you want the clients/```

(Remote the word "that")

2019-05-10 14:21 UTC, sunweaver requested changes
This branch fails to merge now. Please rebase against latest 3.6.x. If possible, fix the comments I made while on it.

2019-05-10 17:13 UTC, uli42 commented
Fixed, including the typos

2019-05-11 07:41 UTC, sunweaver approved these changes

2019-05-11 07:41 UTC, merged

2019-05-13 21:20 UTC, andschwa commented
It looks like this merge brought in the deletion of `xtestext1.h`, which seems to have broken the Debian build from the 3.6.x branch for me.